- platform: template
  sensors:
    diana_home_temperature_status:
      device_class: safety
      value_template: "{% if (states('sensor.diana_tank_temperature')) is equalto 'unknown' or (float(states('sensor.diana_tank_temperature')) is greaterthan 60 and float(states('sensor.diana_tank_temperature')) is lessthan 66) %}false{% else %}{% if(states('device_tracker.84100d1100fb')  is equalto 'home') %}true {% else %}false{% endif %}{% endif %}"
      friendly_name: "Diana's Tank Temperature Warning (Diana home)"
