- platform: template
  sensors:
    saltwater_uv_combined_state:
      value_template: '{{ "on" if (is_state("switch.saltwater_uv_light_5", "on") and is_state("switch.saltwater_uv_pump_2", "on")) else "off" }}'
      friendly_name: "Saltwater UV Combined"
      
- platform: template
  sensors:
    grow_light_combined_state:
      value_template: '{{ "on" if (is_state("switch.grow_light_4", "on") and is_state("switch.grow_light_5", "on") and is_state("switch.grow_light_6", "on")) and is_state("switch.grow_light_7", "on") else "off" }}'
      friendly_name: "Grow Lights Combined"
