- platform: pollen
  zip_code: "48072"
  monitored_conditions:
    - allergy_average_forecasted
    - allergy_average_historical
    - allergy_index_today
    - allergy_index_tomorrow
    - allergy_index_yesterday
    - disease_average_forecasted
    
- platform: template
  sensors:
    allergy_primary_allergen_today:
        value_template: '{{ states.sensor.allergy_index_today.attributes.primary_allergen_name }}'
        friendly_name: "Primary Allergen"
    
- platform: template
  sensors:
    allergy_rating_today:
      value_template: '{{ states.sensor.allergy_index_today.attributes.rating }}'
      friendly_name: "Allergy Rating"
