- platform: darksky
  api_key: !secret darksky_api_key
#  forecast: 
#    - 1
#    - 2
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - humidity
    - hourly_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max
    - cloud_cover
  units: us
  