- platform: mqtt
  state_topic: "/sensor/rtl433"
  name: frontdoor
  qos: 0
  device_class: opening
  value_template: '{% if (value_json.id is equalto 637569) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 637569) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.frontdoor.state}} {% endif %}'