- platform: mqtt
  state_topic: "/sensor/rtl433"
  name: kitchen_pir
  qos: 0
  device_class: motion
  value_template: '{% if (value_json.id is equalto 490804) and (value_json.event is equalto 2) %} on {% else %} off {% endif %}'