- alias: Bar Lights On
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00" 
  action:
    service: switch.turn_on
    entity_id: switch.bar_lights
- alias: Bar Lights Off
  hide_entity: true
  trigger:
    platform: time
    after: '04:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.bar_lights
