- platform: template
  sensors:
    pond_feeding_status:
      device_class: safety
      value_template: "{% if (states('sensor.pond_temperature') is equalto 'unknown' or float(states('sensor.pond_temperature')) is lessthan 50) %}true{% else %}false{% endif %}"
      friendly_name: "Pond Feeding Status"