- platform: template
  sensors:
    pond_temperature_status:
      device_class: safety
      value_template: "{% if (states('sensor.pond_temperature')) is equalto 'unknown' or (float(states('sensor.pond_temperature')) is greaterthan 34 and float(states('sensor.pond_temperature')) is lessthan 86) %}false{% else %}true{% endif %}"
      friendly_name: "Pond Temperature Status"