- alias: Freshwater Sump Light On
  hide_entity: true
  trigger:
    platform: time
    after: '08:00:00' 
  action:
    service: switch.turn_on
    entity_id: switch.freshwater_sump_light_7
- alias: Freshwater Sump Light Off
  hide_entity: true
  trigger:
    platform: time
    after: '23:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.freshwater_sump_light_7
