- platform: mqtt
  state_topic: "/status/3dprinters/3/progress/printing"
  name: 3dprinter3_percent_complete
  friendly_name: 3D Printer 3 Completion
  unit_of_measurement: '%'
  expire_after: 1300
  value_template: "{{ value_json.progress }}"

- platform: mqtt
  state_topic: "/status/3dprinters/3/progress/printing"
  name: 3dprinter3_percent_file
  friendly_name: 3D Printer 3 File
  expire_after: 1300
  value_template: "{{ value_json.path.split('/') | last }}"
  
- platform: command_line
  name: 3dprinter3_state
  command: /home/homeassistant/.homeassistant/scripting/ha_exec.sh ha:poll-printer 3dprinter-3.coogle.local
  value_template: "{{ value_json.state }}"
  scan_interval: 10