- platform: template
  sensors:
    freshwater_temperature_status:
      device_class: safety
      value_template: "{% if (states('sensor.freshwater_tank_temperature')) is equalto 'unknown' or (float(states('sensor.freshwater_tank_temperature')) is greaterthan 70 and float(states('sensor.freshwater_tank_temperature')) is lessthan 82) %}false{% else %}true{% endif %}"
      friendly_name: "Freshwater Temperature Warning"