- platform: mqtt
  name: Diana Switch 1
  command_topic: /diana-power/switch/1
  state_topic: /diana-power/switch/1/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Diana Tank Chiller
  command_topic: /diana-power/switch/2
  state_topic: /diana-power/switch/2/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Diana Grow Lights
  command_topic: /diana-power/switch/3
  state_topic: /diana-power/switch/3/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Diana Tank Lights
  command_topic: /diana-power/switch/4
  state_topic: /diana-power/switch/4/state
  payload_on: "1"
  payload_off: "0"
