- platform: mqtt
  name: Freshwater Sump Switch 1
  command_topic: /freshwater-sump-power/switch/1
  state_topic: /freshwater-sump-power/switch/1/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Freshwater Sump Switch 2
  command_topic: /freshwater-sump-power/switch/2
  state_topic: /freshwater-sump-power/switch/2/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Freshwater Return Pump
  command_topic: /freshwater-sump-power/switch/3
  state_topic: /freshwater-sump-power/switch/3/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Freshwater Sump Switch 4
  command_topic: /freshwater-sump-power/switch/4
  state_topic: /freshwater-sump-power/switch/4/state
  payload_on: "1"
  payload_off: "0"
  