- platform: mqtt
  name: Freshwater Tank Light 2
  command_topic: /freshwater-power/switch/1
  state_topic: /freshwater-power/switch/1/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Freshwater Spotlights
  command_topic: /freshwater-power/switch/2
  state_topic: /freshwater-power/switch/2/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Freshwater Turtle Lights
  command_topic: /freshwater-power/switch/3
  state_topic: /freshwater-power/switch/3/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Freshwater Tank Light 1
  command_topic: /freshwater-power/switch/4
  state_topic: /freshwater-power/switch/4/state
  payload_on: "1"
  payload_off: "0"
  
