- platform: mqtt
  name: Hall Portrait
  command_topic: /hallway-power/switch/1
  state_topic: /hallway-power/switch/1/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Hall Lamp
  command_topic: /hallway-power/switch/2
  state_topic: /hallway-power/switch/2/state
  payload_on: "1"
  payload_off: "0"
