- platform: mqtt
  name: Kitchen Sink Light
  command_topic: /kitchen-sink/switch/2
  state_topic: /kitchen-sink/switch/2/state
  payload_on: "1"
  payload_off: "0"
  
- platform: mqtt
  name: Kitchen Sink Power
  command_topic: /kitchen-sink/switch/1
  state_topic: /kitchen-sink/switch/1/state
  payload_on: "1"
  payload_off: "0"

  
  