- platform: mqtt
  name: Pond Waterfall Pump
  command_topic: /pond/switch/1
  state_topic: /pond/switch/1/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Pond String Lights
  command_topic: /pond/switch/2
  state_topic: /pond/switch/2/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Garden Soaker Pump
  command_topic: /pond/switch/3
  state_topic: /pond/switch/3/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Outdoor Switch 4
  command_topic: /pond/switch/4
  state_topic: /pond/switch/4/state
  payload_on: "1"
  payload_off: "0"
