- platform: mqtt
  name: Back Porch Lights
  command_topic: /porch/switch/2
  state_topic: /porch/switch/2/state
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: Dog House
  command_topic: /porch/switch/1
  state_topic: /porch/switch/1/state
  payload_on: "1"
  payload_off: "0"
