- platform: template
  switches:
    freshwater_tank_lights:
      friendly_name: "Freshwater Tank Lights"
      value_template: "{{ is_state('sensor.freshwater_tank_lights_combined_state', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id:
          - switch.freshwater_display_lights
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.freshwater_display_lights
          
- platform: template
  switches:
    back_porch:
      friendly_name: "Backporch Lights & Power"
      value_template: "{{ is_state('sensor.backporch_lights_combined_state', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id:
          - switch.pond_string_lights
          - switch.back_porch_lights 
          - switch.back_porch_power
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.pond_string_lights
          - switch.back_porch_lights
          - switch.back_porch_power

- platform: template
  switches:
    saltwater_lights:
      friendly_name: "Saltwater Lights"
      value_template: "{{ is_state('sensor.saltwater_lights_combined_state', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id:
          - switch.saltwater_light_1
          - switch.saltwater_light_2
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.saltwater_light_1
          - switch.saltwater_light_2

- platform: template
  switches:
    grow_lights:
      friendly_name: "Grow Lights"
      value_template: "{{ is_state('sensor.grow_light_combined_state', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: 
          - switch.grow_light_4
          - switch.grow_light_5
          - switch.grow_light_6
          - switch.grow_light_7
          - switch.grow_light_8
          - switch.grow_light_9
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.grow_light_4
          - switch.grow_light_5
          - switch.grow_light_6
          - switch.grow_light_7
          - switch.grow_light_8
          - switch.grow_light_9

- platform: template
  switches:
    saltwater_uv:
      friendly_name: 'Saltwater UV'
      value_template: "{{ is_state('sensor.saltwater_uv_combined_state', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id:
          - switch.saltwater_uv_light_5
          - switch.saltwater_uv_pump_2
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.saltwater_uv_light_5
          - switch.saltwater_uv_pump_2
