Security:
  view: yes
  icon: mdi:security-home
  control: hidden
  entities:
    - group.security_sensors
    - group.security_pets
    - camera.living_room
    - camera.backyard
    - camera.front_door
