Settings:
  view: yes
  icon: mdi:settings
  control: hidden
  entities:
    - group.settings_alerts
    - group.settings_flooding
    - group.settings_sarah
    - group.settings_house
    - group.settings_vacation
    - group.settings_coogleiot
    - group.sarah_weblinks
    - group.settings_savings
    - configurator.philips_hue