- platform: template
  sensors:
    backporch_lights_combined_state:
      value_template: '{{ "on" if (is_state("switch.back_porch_lights", "on") and is_state("switch.pond_string_lights", "on") and is_state("switch.back_porch_power", "on")) else "off" }}'
      friendly_name: "Back Porch Lighting"
