- platform: mqtt
  state_topic: "/sensor/rtl433/9134"
  name: outdoor_temperature
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature_C }}'
  expire_after: 600
  
- platform: mqtt
  state_topic: "/sensor/rtl433/9134"
  name: outdoor_humidity
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'
  expire_after: 600
