mqtt:
  host: localhost
  preface: dash
buttons:
  B4:7C:9C:78:6A:92: /button/waterfall-activate
  AC:63:BE:E2:4A:3B: /button/backyard-lights
  B4:7C:9C:22:60:48: /button/poo-tracker
  40:B4:CD:F3:0B:F5: /button/bedtime
  40:B4:CD:20:8F:33: /button/grow-lights   
  68:54:FD:C1:3B:B1: /button/bedtime
  68:54:FD:E9:93:C2: /button/workshop-light
  FC:A6:67:51:AB:C6: /button/workshop-exhaust
  50:F5:DA:E2:A8:66: /button/office-desklamp
  B4:7C:9C:D6:58:C2: /button/backyard-lights