pond_timeout:
  name: Pond Auto Timeout Minutes
  initial: 60
  min: 5
  max: 180
  step: 5
  icon: mdi:timer

peristalic_doser_turns:
  name: Doser Turns
  initial: 120
  min: 0
  max: 360
  step: 5
  icon: mdi:flask-outline
  