pond_timeout:
  name: Pond Auto Timeout Minutes
  initial: 60
  min: 5
  max: 180
  step: 5
  icon: mdi:timer

peristalic_doser_potassium_runtime:
  name: Potassium Doser Seconds
  initial: 240
  min: 0
  max: 360
  step: 5
  icon: mdi:settings

peristalic_doser_nutrient_runtime:
  name: Nutrient Doser Seconds
  initial: 240
  min: 0
  max: 360
  step: 5
  icon: mdi:settings

saltwater_feeder_turns:
  name: Saltwater Feeder Turns
  initial: 1
  min: 0
  max: 10
  step: 1
  icon: mdi:settings
  
