- platform: template
  lights:
    dining_room_lights:
      friendly_name: "Dining Room Lights"
      level_template: "{{ states('sensor.dining_room_lights_brightness') | int }}"
      value_template: "{{ (states('sensor.dining_room_lights_brightness') | int > 0)  }}"
      turn_on:
        - service: light.turn_on
          data:
            entity_id: light.dining_room_1
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.dining_room_2
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.dining_room_3
            brightness: 254
        - service: switch.turn_on
          entity_id: switch.flag_spotlight
        - service: switch.turn_on
          entity_id: switch.dining_room_cabinet
      turn_off:
        - service: light.turn_off
          entity_id: light.dining_room_1
        - service: light.turn_off
          entity_id: light.dining_room_2
        - service: light.turn_off
          entity_id: light.dining_room_3
        - service: switch.turn_off
          entity_id: switch.flag_spotlight
        - service: switch.turn_off
          entity_id: switch.dining_room_cabinet
      set_level:
        - service: light.turn_on
          data_template: 
            entity_id: light.dining_room_1
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.dining_room_2
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.dining_room_3
            brightness: "{{ brightness }}"
          
      