- platform: template
  lights:
    kitchen_lights:
      friendly_name: "Kitchen Lights"
      level_template: "{{ states('sensor.kitchen_lights_brightness') | int }}"
      value_template: "{{ (states('sensor.kitchen_lights_brightness') | int > 0)  }}"
      turn_on:
        - service: light.turn_on
          data:
            entity_id: light.kitchen_1
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.kitchen_2
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.kitchen_3
            brightness: 254
        - service: switch.turn_on
          entity_id: switch.kitchen_sink_light
      turn_off:
        - service: light.turn_off
          entity_id: light.kitchen_1
        - service: light.turn_off
          entity_id: light.kitchen_2
        - service: light.turn_off
          entity_id: light.kitchen_3
        - service: switch.turn_off
          entity_id: switch.kitchen_sink_light
      set_level:
        - service: light.turn_on
          data_template: 
            entity_id: light.kitchen_1
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.kitchen_2
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.kitchen_3
            brightness: "{{ brightness }}"
          
      