- platform: template
  lights:
    living_room_lights:
      friendly_name: "Living Room Lights"
      level_template: "{{ states('sensor.living_room_lights_brightness') | int }}"
      value_template: "{{ (states('sensor.living_room_lights_brightness') | int > 0)  }}"
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.christmas_tree
        - service: light.turn_on
          data:
            entity_id: light.living_room_1
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.living_room_2
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.living_room_3
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.living_room_4
            brightness: 254
        - service: switch.turn_on
          entity_id: switch.accent_lighting
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.christmas_tree
        - service: light.turn_off
          data:
            entity_id: light.living_room_1
        - service: light.turn_off
          data:
            entity_id: light.living_room_2
        - service: light.turn_off
          data:
            entity_id: light.living_room_3
        - service: light.turn_off
          data:
            entity_id: light.living_room_4
        - service: switch.turn_off
          entity_id: switch.accent_lighting
      set_level:
        - service: light.turn_on
          data_template: 
            entity_id: light.living_room_1
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.living_room_2
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.living_room_3
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.living_room_4
            brightness: "{{ brightness }}"
          
      