- platform: template
  lights:
    master_bedroom_lights:
      friendly_name: "Master Bedroom Lights"
      level_template: "{{ states('sensor.master_bedroom_lights_brightness') | int }}"
      value_template: "{{ (states('sensor.master_bedroom_lights_brightness') | int > 0)  }}"
      turn_on:
        - service: light.turn_on
          data:
            entity_id: light.master_bedroom_1
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.master_bedroom_2
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.master_closet
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.jewelry_table
            brightness: 254
      turn_off:
        - service: light.turn_off
          data:
            entity_id: light.master_bedroom_1
        - service: light.turn_off
          data:
            entity_id: light.master_bedroom_2
        - service: light.turn_off
          data:
            entity_id: light.master_closet
        - service: light.turn_off
          data:
            entity_id: light.jewelry_table
      set_level:
        - service: light.turn_on
          data_template: 
            entity_id: light.master_bedroom_1
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.master_bedroom_2
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.master_closet
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.jewelry_table
            brightness: "{{ brightness }}"