- platform: template
  lights:
    office_lights:
      friendly_name: "Office Lights"
      level_template: "{{ states('sensor.office_lights_brightness') | int }}"
      value_template: "{{ (states('sensor.office_lights_brightness') | int > 0)  }}"
      turn_on:
        - service: light.turn_on
          data: 
            entity_id: light.office_1
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.office_2
            brightness: 254
        - service: switch.turn_on
          entity_id: switch.office_desk_lamp
      turn_off:
        - service: light.turn_off
          entity_id: light.office_1
        - service: light.turn_off
          entity_id: light.office_2
        - service: switch.turn_off
          entity_id: switch.office_desk_lamp
      set_level:
        - service: light.turn_on
          data_template: 
            entity_id: light.office_1
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.office_2
            brightness: "{{ brightness }}"
          
      