- platform: template
  lights:
    upstairs_bathroom_lights:
      friendly_name: "Upstairs Bathroom Lights"
      level_template: "{{ states('sensor.upstairs_bathroom_lights_brightness') | int }}"
      value_template: "{{ (states('sensor.upstairs_bathroom_lights_brightness') | int > 0)  }}"
      turn_on:
        - service: light.turn_on
          data:
            entity_id: light.upstairs_bathroom_1
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.upstairs_bathroom_2
            brightness: 254
        - service: light.turn_on
          data:
            entity_id: light.upstairs_shower
            brightness: 254
      turn_off:
        - service: light.turn_off
          entity_id: light.upstairs_bathroom_1
        - service: light.turn_off
          entity_id: light.upstairs_bathroom_2
        - service: light.turn_off
          entity_id: light.upstairs_shower
      set_level:
        - service: light.turn_on
          data_template: 
            entity_id: light.upstairs_bathroom_1
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.upstairs_bathroom_2
            brightness: "{{ brightness }}"
        - service: light.turn_on
          data_template:
            entity_id: light.upstairs_shower
            brightness: "{{ brightness }}"
      