- platform: template
  sensors:
    freezer_temperature_status:
      device_class: safety
      value_template: "{% if (states('sensor.freezer_temperature')) is equalto 'unknown' or (float(states('sensor.freezer_temperature')) is greaterthan 30) %}true{% else %}false{% endif %}"
      friendly_name: "Freezer Temperature Warning"