- alias: Push Octoprint Updates to MQTT
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.3d_printer_current_state
    - platform: state
      entity_id: sensor.3d_printer_job_percentage
    - platform: event
      event_type: homeassistant_start
  action:
    - service: mqtt.publish
      data_template:
        topic: '/status/octoprint'
        retain: true
        payload: >
          {
            "current_state" : "{{ states('sensor.3d_printer_current_state') }}",
            "job_percentage" : {{ states('sensor.3d_printer_job_percentage') }}
          } 
