- platform: aruba
  host: router-outside.coogle.local
  username: admin
  password: !secret router_outside_password

- platform: ddwrt
  host: 192.168.1.1
  username: !secret router_username
  password: !secret router_password

- platform: icloud
  username: john@coggeshall.org
  password: !secret icloud_password
  account_name: Johns iCloud

- platform: automatic
  client_id: !secret automatic_client_id
  secret: !secret automatic_client_secret
  current_location: true

- platform: mqtt_json
  devices:
    hercules_collar: /status/pets/265889
